name = "simulation 1"
rep = 100
output = "save.RDS"


[covariate]
"wt+age ~ rmvnorm(c(80,45), dmat(40,30))"



[period]
[period.a]
amt=100
ii=12
add=100
[period.b]
amt=200
ii=12
addl=100

[sequence]
[sequence.1]
["a","b"]
[sequence.2]
["b","a"]

[arm]
[arm.1]
nid = 30
sequence = 1
output = "tgrid(0,240,1)"

[arm.2]
nid = 30
sequence = 2
ouput = "tgrid(0,120,1)"


