---
title: "Untitled"
output: 
  md_document:
    variant: markdown_github
---


# Scripted simulation runs with `mrgsolve`

```{r,echo=FALSE}
library(knitr)
knitr::opts_chunk$set(comment='.', message=FALSE)
```

```{r}
library(mrgsim)
library(mrgsolve)
library(dplyr)
```


## Load a model
```{r}
mod <- mread("popex", modlib())

param(mod)
```

## Load a scripted simulation run
```{r}
run <- load_run("inst/yaml/foo.yaml")
```


## Simulate

```{r,eval=FALSE}
out <- sim_run(mod,run)
```

```{r,eval=TRUE,echo=FALSE}
runtime <- system.time(out <- sim_run(mod,run))
```


```{r}
runtime
```

```{r}
dim(out)

out %>%
  group_by(arm) %>% 
  filter(time==4032) %>%
  summarise(Mean = mean(DV), Min = min(DV), Max = max(DV), N=n())
```


## The simulation run specification
```{r,echo=FALSE, comment=" "}
yam <- readLines("inst/yaml/foo.yaml")
cat(yam, sep="\n")
```

## Run specification for pediatric / adult pk
```{r,echo=FALSE, comment=" "}
yam <- readLines("inst/yaml/ped_adult.yaml")
cat(yam, sep="\n")
```


## Run specification details


The run has arms
```{r}
arms(run)
```

treatment sequences
```{r}
sequences(run)
```

treatment periods
```{r}
run$periods
```

covariate sets
```{r}
covsets(run)
```

sampling times
```{r}
run$designs
```

